esiea_blog_homepage:
    path:    /
    defaults:    {_controller:EsieaBlogBundle:Default:index}

esiea_blog_vue:
    pattern: /{id}
    defaults: { _controller: EsieaBlogBundle:Default:vue }
    requirements:
        id: \d+

esiea_blog_ajouter:
    pattern: /ajouter
    defaults: { _controller: EsieaBlogBundle:Default:ajouter }

esiea_blog_modifier:
    pattern: /modifier/{id}
    defaults: { _controller: EsieaBlogBundle:Default:modifier }
    requirements:
        id: \d+

esiea_blog_supprimer:
    pattern: /acteur/supprimer/{id}
    defaults: { _controller: EsieaBlogBundle:Default:supprimer }
    requirements:
        id: \d+

esiea_blog_article:
    pattern: /article/{id}
    defaults: { _controller: EsieaBlogBundle:Default:article }
    requirements:
        id: \d+

esiea_blog_login:
    pattern: /login
    defaults: { _controller: EsieaBlogBundle:Default:login }
